#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASS}
#spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
#management.endpoints.web.exposure.include=info
#management.endpoint.health.show-details=always
#management.endpoints.web.base-path=/actuator
## JWT secret key
#token.secret.key=${JWT_KEY}
##24 hr
#
#token.expirationms=86400000
#token.refresh.expirationms=1209600000
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=110MB
#upload.directory=C:/uploads
#info.app.version=${project.version}
#pool-name: Main-Pool
#connection-test-query: SELECT 1
#connection-timeout: 60000
#minimum-idle: 2
#maximum-pool-size: 10
#auto-commit: false
#idle-timeout: 35000
#max-lifetime: 600000
#validation-timeout: 3000
############
#spring.jpa.show-sql=true
#
### Enable Hibernate 2nd level cache
##spring.jpa.properties.hibernate.cache.use_second_level_cache=true
##spring.jpa.properties.hibernate.cache.use_query_cache=true
###spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.jcache.internal.JCacheRegionFactory
##
### Specify JCache provider as Caffeine
##spring.jpa.properties.hibernate.javax.cache.provider=org.springframework.cache.jcache.JCacheManagerFactoryBean
##spring.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.internal.NoCacheProvider
#
## Load caffeine configuration
#spring.jpa.properties.hibernate.javax.cache.uri=classpath:ehcache.xml
#

#
## Format SQL for better readability
#spring.jpa.properties.hibernate.format_sql=true
#
## Log actual parameter values
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
## Log file settings
#logging.file.name=logs/application.log   # Change path as needed
#logging.file.path=logs
#logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
#########################################################################################

spring.profiles.active=prod
