spring.web.resources.add-mappings=true
spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USER_PROD}
spring.datasource.password=${DB_PASS_PROD}
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
management.metrics.tags.application=settlement-back
# JWT secret key
token.secret.key=${JWT_KEY_PROD}
#24 hr
token.expirationms=86400000
token.refresh.expirationms=1209600000
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=110MB
upload.directory=/opt/settlement/storage
info.app.version=${project.version}
pool-name=Main-Pool
connection-test-query=SELECT 1
connection-timeout=60000
minimum-idle=2
maximum-pool-size=10
auto-commit=false
idle-timeout=35000
max-lifetime=600000
validation-timeout=3000
spring.jpa.properties.hibernate.javax.cache.uri=classpath:ehcache.xml
spring.mvc.async.request-timeout=40s
slack.webhook.url=${SLACK_WEBHOOK_URL_PROD}
app.cors.allowed-origins=https://settlement.energo-pro.ge
